name: 'Initialize'
description: 'Checkout repo and install dependencies'
inputs:
  setuptools:
    description: 'If true, use setuptools to install the requirements.'
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install runtime dependencies
      run: python -m pip install --only-binary ':all:' -r requirements.txt --upgrade
      shell: bash
      if: ${{ inputs.setuptools == 'false' }}
    - name: Install latest version of runtime dependency libraries
      run: python setup.py install
      shell: bash
      continue-on-error: true
      if: ${{ inputs.setuptools == 'true' }}
    - name: Install test dependencies
      run: python -m pip install --only-binary ':all:' -r test_requirements.txt --upgrade
      shell: bash
    - name: Install citrine
      run: python -m pip install --only-binary ':all:' -e . --upgrade
      shell: bash
