# Developmental Docker container
FROM python:3.8

WORKDIR /src
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY test_requirements.txt .
RUN pip install -r test_requirements.txt

COPY . .
RUN python setup.py develop
CMD pytest
