FROM python:3.9

RUN mkdir /opt/app
COPY . /opt/app

WORKDIR /opt/app

RUN pip install sphinx
RUN pip install sphinxcontrib-apidoc
RUN pip install sphinx-rtd-theme
RUN pip install -e .

WORKDIR /opt/app/docs

ENV SPHINX_APIDOC_OPTIONS="members,undoc-members,inherited-members,show-inheritance"

RUN make html
