name: PR Tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  pr-tests:
    uses: CitrineInformatics/common-gh-actions/.github/workflows/run-tests.yml@v2.0
    with:
      src: src/citrine
      skip_39: true
      include_314: true
