name: PR Tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  pr-tests:
    uses: CitrineInformatics/common-gh-actions/.github/workflows/run-tests.yml@v1.1
    with:
      src: src/citrine
      include_313: true
      skip_38: false
