name: PR Tests

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  pr-tests:
    uses: CitrineInformatics/common-gh-actions/.github/workflows/run-tests.yml@v1
    with:
      src: src/citrine
